# Generated by Django 4.2.7 on 2023-11-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siscarb_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historico",
            name="data_calculo",
            field=models.DateTimeField(),
        ),
    ]
